import React from 'react';

export function FraudAlertsView({
  flaggedTransactions = [],
  alerts = [],
  modelInfo,
  onDismissAlert,
  onInspectTransaction
}) {
  return (
    <div>
      {/* Mandatory Experimental Disclaimer Banner */}
      <div className="disclaimer-banner">
        <span style={{ fontSize: '1.25rem' }}>⚠️</span>
        <div>
          <strong>EXPERIMENTAL ANOMALY DETECTION NOTICE:</strong>
          <div>
            The fraud scores and alerts displayed on this platform are generated by an experimental scikit-learn Isolation Forest model and heuristics for developer demonstration. They are <strong>not</strong> intended for making real-world financial, legal, or payment decisions.
          </div>
        </div>
      </div>

      {/* Model Metadata Summary */}
      <div className="metrics-grid">
        <div className="metric-card">
          <span className="metric-label">Model Engine</span>
          <span style={{ fontSize: '1.2rem', fontWeight: 700, marginTop: '4px' }}>
            {modelInfo?.model_name || 'Isolation Forest (scikit-learn)'}
          </span>
          <span className="metric-subtitle">Unsupervised outlier & anomaly detection</span>
        </div>

        <div className="metric-card">
          <span className="metric-label">Contamination Rate</span>
          <span className="metric-value" style={{ fontSize: '1.5rem' }}>
            {(modelInfo?.contamination ? modelInfo.contamination * 100 : 3)}%
          </span>
          <span className="metric-subtitle">Trained on baseline financial distribution</span>
        </div>

        <div className="metric-card">
          <span className="metric-label">Active Flags</span>
          <span className="metric-value fraud">{flaggedTransactions.length}</span>
          <span className="metric-subtitle">Flagged anomalous transactions</span>
        </div>
      </div>

      {/* Flagged Transactions Deep-Dive */}
      <div className="panel" style={{ marginBottom: '24px' }}>
        <div className="panel-header">
          <div>
            <h3 className="panel-title">Flagged Transaction Anomalies</h3>
            <span style={{ fontSize: '0.8rem', color: 'var(--text-dim)' }}>
              Transactions that triggered Isolation Forest outliers or high-risk merchant heuristics
            </span>
          </div>
        </div>

        {flaggedTransactions.length === 0 ? (
          <div className="empty-state">
            <span style={{ fontSize: '2rem', display: 'block', marginBottom: '8px' }}>🛡️</span>
            <h3>No Suspicious Transactions Detected</h3>
            <p>All recorded transactions align with standard consumer spending baselines.</p>
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
            {flaggedTransactions.map((tx) => (
              <div
                key={tx.id}
                style={{
                  backgroundColor: 'var(--bg-input)',
                  border: '1px solid rgba(239, 68, 68, 0.4)',
                  borderRadius: 'var(--radius-md)',
                  padding: '18px 20px',
                  display: 'flex',
                  flexDirection: 'column',
                  gap: '10px'
                }}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '8px' }}>
                  <div>
                    <span style={{ fontWeight: 700, fontSize: '1.05rem', color: '#fca5a5' }}>
                      {tx.merchant || tx.description}
                    </span>
                    <span style={{ marginLeft: '12px', fontSize: '0.8rem', color: 'var(--text-dim)' }}>
                      {tx.date ? new Date(tx.date).toLocaleString() : ''}
                    </span>
                  </div>

                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                    <span className="pill pill-fraud">
                      Risk Score: {Math.round((tx.fraud_score || 0.85) * 100)} / 100
                    </span>
                    <span className="amount-display amount-expense" style={{ fontSize: '1.15rem' }}>
                      ${Number(tx.amount).toFixed(2)}
                    </span>
                  </div>
                </div>

                <div style={{
                  backgroundColor: 'rgba(239, 68, 68, 0.08)',
                  borderLeft: '3px solid var(--danger)',
                  padding: '10px 14px',
                  borderRadius: '0 4px 4px 0',
                  fontSize: '0.85rem'
                }}>
                  <strong>Anomaly Diagnostic: </strong>
                  <span>{tx.fraud_reason || 'Multi-factor deviation from normal spending volume and time.'}</span>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* System Security Alerts Feed */}
      <div className="panel">
        <div className="panel-header">
          <h3 className="panel-title">Real-Time Alert Feed</h3>
          <span style={{ fontSize: '0.8rem', color: 'var(--text-dim)' }}>
            Generated asynchronously by RabbitMQ event workers
          </span>
        </div>

        {alerts.length === 0 ? (
          <p style={{ textAlign: 'center', padding: '24px', color: 'var(--text-dim)' }}>
            No recent system alerts.
          </p>
        ) : (
          <div>
            {alerts.map((alert) => (
              <div
                key={alert.id}
                className={`alert-card ${
                  alert.type === 'FRAUD_ALERT'
                    ? 'alert-fraud'
                    : alert.type === 'BUDGET_EXCEEDED'
                    ? 'alert-budget-exceeded'
                    : 'alert-budget-warning'
                }`}
              >
                <div>
                  <div className="alert-title">{alert.title}</div>
                  <div className="alert-desc">{alert.message}</div>
                  <div className="alert-meta">
                    {alert.createdAt ? new Date(alert.createdAt).toLocaleString() : ''}
                  </div>
                </div>

                <button
                  className="btn btn-secondary btn-sm"
                  onClick={() => onDismissAlert(alert.id)}
                  title="Dismiss Alert"
                >
                  Dismiss
                </button>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
